name       : networkmanager-libreswan
version    : 1.2.12
release    : 3
source     :
    - https://download.gnome.org/sources/NetworkManager-libreswan/1.2/NetworkManager-libreswan-1.2.12.tar.xz : 57a8a5e4537e41260df50fe4ddc16a09cb909b4ae19833a53ccac12d1234a6f6
license    : GPL-2.0-or-later
component  : network.base
summary    : Libreswan VPN client plugin for NetworkManager
description: |
    Libreswan VPN client plugin for NetworkManager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libsecret-unstable)
    - libnma-devel
rundeps    :
    - libreswan
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
