name       : networkmanager-libreswan
version    : 1.2.14
release    : 7
source     :
    - https://download.gnome.org/sources/NetworkManager-libreswan/1.2/NetworkManager-libreswan-1.2.14.tar.xz : 91cf0395d1b562d6f8c894cdbfe0624adcf1b679bf0b6954fb7d9b71e14387b7
license    : GPL-2.0-or-later
component  : network.base
summary    : Libreswan VPN client plugin for NetworkManager
description: |
    Libreswan VPN client plugin for NetworkManager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - libreswan
setup      : |
    # Only dbus-1 goes into sysconfdir (etc by default) so move it
    %configure --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
