name       : networkmanager-libreswan
version    : 1.2.16
release    : 12
source     :
    - https://download.gnome.org/sources/NetworkManager-libreswan/1.2/NetworkManager-libreswan-1.2.16.tar.xz : c6b7ef71f6587d9c09e37ece6c20b4c4a5456f80c90e5c9eb6ec89e8ec38e654
license    : GPL-2.0-or-later
component  : network.base
summary    : Libreswan VPN client plugin for NetworkManager
description: |
    Libreswan VPN client plugin for NetworkManager
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - libreswan
setup      : |
    # Only dbus-1 goes into sysconfdir (etc by default) so move it
    %configure --sysconfdir=/usr/share --with-gtk4
build      : |
    %make
install    : |
    %make_install
