name       : networkmanager-libreswan
version    : 1.2.10
release    : 1
source     :
    - https://download.gnome.org/sources/NetworkManager-libreswan/1.2/NetworkManager-libreswan-1.2.10.tar.xz : e169b106d9227c4b0f8f2ef00f56fd435a87e27f3c0485d1189814a112116c42
license    : GPL-2.0-or-later
component  : network.base
summary    : Libreswan VPN client plugin for NetworkManager
description: |
    Libreswan VPN client plugin for NetworkManager
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-unstable)
rundeps    :
    - libreswan
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
